name: auth0-middleware
description: 'A comprehensive Auth0 SSO authentication middleware for RoadRunner that provides enterprise-grade authentication capabilities with flexible URL protection patterns and seamless integration with PHP applications.'
category: http
owner: butschster
dependencies:
  - rpc
  - http
  - logger
author:
  name: Pavel Buchnev
  email: butschster@gmail.com
license: MIT